### ISSUE TITLE
Installation breaks: ModuleNotFoundError: No module named 'Cython'

### ISSUE THREAD

**Issue by mdozmorov** [WXlab-NJMU/scrna-recom#1]
Installing on a Mac with `mamba env create -f scrna-recom_osx-64.yaml -n scrna-recom`. It breaks, apparently, Cython cannot be found. A part of the error output:
```{bash}
Collecting velocyto==0.17.17
  Downloading velocyto-0.17.17.tar.gz (198 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.9/198.9 kB 5.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

Pip subprocess error:
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/mf/dwx4qv115sz5vrdwyxkllf_c0000gq/T/pip-install-g2hjbd1q/velocyto_c3a4ab5870be40c8a64405bb7dacacc1/setup.py", line 16, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      ['/private/var/folders/mf/dwx4qv115sz5vrdwyxkllf_c0000gq/T/pip-install-g2hjbd1q/velocyto_c3a4ab5870be40c8a64405bb7dacacc1/setup.py', 'egg_info', '--egg-base', '/private/var/folders/mf/dwx4qv115sz5vrdwyxkllf_c0000gq/T/pip-pip-egg-info-ygishq88']
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

failed

CondaEnvException: Pip failed
```

I tried to add cython to `scrna-recom_osx-64.yaml` - it didn't help with the strange permissions issue. The same issue occur if I recreate an empty `scrna-recom` and install cython in there `mamba install -c anaconda cython`. The error output is long, here's some:
```{bash}
    Traceback (most recent call last):
      File "/Users/mdozmorov/miniconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
      File "/Users/mdozmorov/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 926, in exception_converter
        raise e
      File "/Users/mdozmorov/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 919, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/Users/mdozmorov/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 877, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/Users/mdozmorov/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 748, in do_call
        exit_code = install(args, parser, "install")
      File "/Users/mdozmorov/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 468, in install
        index = load_channels(pool, channels, repos)
      File "/Users/mdozmorov/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 142, in load_channels
        index = get_index(
      File "/Users/mdozmorov/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 123, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Download error (23) Failed writing received data to disk/application [https://conda.anaconda.org/t/<TOKEN>/anaconda/noarch/repodata.json.zst]
    Failure writing output to destination
```
Any suggestions?

**Comment by Sue9104** [comment]
@mdozmorov You can try `pip install Cython`

**Comment by mdozmorov** [comment]
Thanks, @Sue9104. I did try that, and tried again with the same result as the last error. Specifically, I activated the `scrna-recom` environment, installed `pip install Cython`, and did `mamba env update --file scrna-recom_osx-64.yaml --prune`. The full error report:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/user/miniconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
      File "/Users/user/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 49, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/user/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 118, in wrapper
        return_value = func(*args, **kwargs)
      File "/Users/user/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_update.py", line 139, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
      File "/Users/user/miniconda3/lib/python3.9/site-packages/mamba/mamba_env.py", line 55, in mamba_install
        index = load_channels(pool, channel_urls, repos, prepend=False)
      File "/Users/user/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 142, in load_channels
        index = get_index(
      File "/Users/user/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 123, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Download error (23) Failed writing received data to disk/application [https://conda.anaconda.org/t/<TOKEN>/anaconda/noarch/repodata.json.zst]
    Failure writing output to destination

`$ /Users/user/miniconda3/condabin/mamba update --file scrna-recom_osx-64.yaml --prune`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=scrna-recom
                CONDA_EXE=/Users/user/miniconda3/bin/conda
             CONDA_PREFIX=/Users/user/miniconda3/envs/scrna-recom
           CONDA_PREFIX_1=/Users/user/miniconda3
    CONDA_PROMPT_MODIFIER=(scrna-recom)
         CONDA_PYTHON_EXE=/Users/user/miniconda3/bin/python
               CONDA_ROOT=/Users/user/miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/Users/user/.cargo/bin:/Users/user/miniconda3/envs/scrna-rec
                          om/bin:/Users/user/miniconda3/condabin:/bin:/usr/bin:/usr/sbin:/u
                          sr/local/bin:/usr/local/sbin:/Users/user/.local:/Users/user/
                          .local/bin:/Users/user/Library/Python/3.9/bin:/usr/local/gfortran
                          /bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : scrna-recom
    active env location : /Users/user/miniconda3/envs/scrna-recom
            shell level : 2
       user config file : /Users/user/.condarc
 populated config files : /Users/user/.condarc
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=13.4.1=0
                          __unix=0=0
       base environment : /Users/user/miniconda3  (writable)
      conda av data dir : /Users/user/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/user/miniconda3/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /Users/user/miniconda3/envs
                          /Users/user/.conda/envs
               platform : osx-64
             user-agent : conda/23.5.0 requests/2.29.0 CPython/3.9.16 Darwin/22.5.0 OSX/13.4.1
                UID:GID : 503:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by Sue9104** [comment]
@mdozmorov  `RuntimeError: Download error (23) Failed writing received data to disk/application` seems that you should check whether you have enough space available first.

Besides, I made a little change on scrna-recom_osx-64.yaml (f14e0e5f61e12a9d92163a6c03a335ea558071e4) to keep with recent commits, and you could start with that file.

Good luck!

**Comment by mdozmorov** [comment]
Thanks, @Sue9104, I managed to make it work. I had to remove the version restriction for `pydata-sphinx-theme==0.7.2` as it caused a conflict. Will play with it, thanks for creating this pipeline.

And a small improvement. On this page, https://github.com/WXlab-NJMU/scrna-recom/wiki/install, this command should be `mamba env create -f build/scrna-recom_linux**-64**.yaml -n scrna-recom`

**Comment by mdozmorov** [comment]
Of note, installation on a Linux system similarly failed with cython not being installed. Activating the environment, doing `pip install cython` and `mamba env update --file scrna-recom_osx-64.yaml --prune` solved the problem. But it may be something you want to incorporated either in the installation instructions or in the yaml files.

On Linux, I had libzlib and tiledb version conflict. Removing hard version requirements in the yaml file helped.

**Comment by Sue9104** [comment]
Thanks, I've added it at df7812eebcc3b68e57386122e9d052902c54d97c
